### ISSUE TITLE
Morning Peer-to-Peer code review

### ISSUE THREAD

**Issue by Ismailco** [jerryowusu/Web-Summit-Accra#2]
- you can Fix the Screenshot in the README file, by removing the zoom preview
- it will be better to use the navigation in the About Page on README
- You can put the scripts inside of the head tag, and add defer keyword so that the scripts load after your Html is loaded
- Overall, the Project looks awesome. Nice animation for the mobile menu.

**Comment by jerryowusu** [comment]
Resolved. Thanks a lot
